/*
 * data.js — static tournament data for the Mundial 2026 wallchart.
 *
 * Pure constants only (teams, broadcasters, venues, fixtures, the FIFA
 * Annex C third-place map, knockout schedule and bracket layout). No logic
 * or DOM access lives here. Loaded before script.js in index.html; because
 * these are classic (non-module) scripts, the top-level const/let below are
 * shared with script.js through the page's global lexical scope.
 */

/* All 48 teams: ISO-style code -> { name, flag, fifaRank }
	 fifaRank = position in the FIFA Men's World Ranking of 11 June 2026,
	 used automatically as the final tie-breaker. */
const TEAMS = {
  MEX: { name: "México", flag: "🇲🇽", fifaRank: 14 },
  KOR: { name: "Coreia do Sul", flag: "🇰🇷", fifaRank: 25 },
  RSA: { name: "África do Sul", flag: "🇿🇦", fifaRank: 60 },
  CZE: { name: "Chéquia", flag: "🇨🇿", fifaRank: 40 },
  CAN: { name: "Canadá", flag: "🇨🇦", fifaRank: 30 },
  SUI: { name: "Suíça", flag: "🇨🇭", fifaRank: 19 },
  QAT: { name: "Catar", flag: "🇶🇦", fifaRank: 56 },
  BIH: { name: "Bósnia e Herzegovina", flag: "🇧🇦", fifaRank: 64 },
  BRA: { name: "Brasil", flag: "🇧🇷", fifaRank: 6 },
  MAR: { name: "Marrocos", flag: "🇲🇦", fifaRank: 7 },
  SCO: { name: "Escócia", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", fifaRank: 42 },
  HAI: { name: "Haiti", flag: "🇭🇹", fifaRank: 83 },
  USA: { name: "Estados Unidos", flag: "🇺🇸", fifaRank: 17 },
  PAR: { name: "Paraguai", flag: "🇵🇾", fifaRank: 41 },
  AUS: { name: "Austrália", flag: "🇦🇺", fifaRank: 27 },
  TUR: { name: "Turquia", flag: "🇹🇷", fifaRank: 22 },
  GER: { name: "Alemanha", flag: "🇩🇪", fifaRank: 10 },
  ECU: { name: "Equador", flag: "🇪🇨", fifaRank: 23 },
  CIV: { name: "Costa do Marfim", flag: "🇨🇮", fifaRank: 33 },
  CUW: { name: "Curaçao", flag: "🇨🇼", fifaRank: 82 },
  NED: { name: "Países Baixos", flag: "🇳🇱", fifaRank: 8 },
  JPN: { name: "Japão", flag: "🇯🇵", fifaRank: 18 },
  TUN: { name: "Tunísia", flag: "🇹🇳", fifaRank: 45 },
  SWE: { name: "Suécia", flag: "🇸🇪", fifaRank: 38 },
  BEL: { name: "Bélgica", flag: "🇧🇪", fifaRank: 9 },
  IRN: { name: "Irão", flag: "🇮🇷", fifaRank: 20 },
  EGY: { name: "Egito", flag: "🇪🇬", fifaRank: 29 },
  NZL: { name: "Nova Zelândia", flag: "🇳🇿", fifaRank: 85 },
  ESP: { name: "Espanha", flag: "🇪🇸", fifaRank: 2 },
  URU: { name: "Uruguai", flag: "🇺🇾", fifaRank: 16 },
  KSA: { name: "Arábia Saudita", flag: "🇸🇦", fifaRank: 61 },
  CPV: { name: "Cabo Verde", flag: "🇨🇻", fifaRank: 67 },
  FRA: { name: "França", flag: "🇫🇷", fifaRank: 3 },
  SEN: { name: "Senegal", flag: "🇸🇳", fifaRank: 15 },
  NOR: { name: "Noruega", flag: "🇳🇴", fifaRank: 31 },
  IRQ: { name: "Iraque", flag: "🇮🇶", fifaRank: 57 },
  ARG: { name: "Argentina", flag: "🇦🇷", fifaRank: 1 },
  AUT: { name: "Áustria", flag: "🇦🇹", fifaRank: 24 },
  ALG: { name: "Argélia", flag: "🇩🇿", fifaRank: 28 },
  JOR: { name: "Jordânia", flag: "🇯🇴", fifaRank: 63 },
  POR: { name: "Portugal", flag: "🇵🇹", fifaRank: 5 },
  COL: { name: "Colômbia", flag: "🇨🇴", fifaRank: 13 },
  UZB: { name: "Uzbequistão", flag: "🇺🇿", fifaRank: 50 },
  COD: { name: "RD Congo", flag: "🇨🇩", fifaRank: 46 },
  ENG: { name: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", fifaRank: 4 },
  CRO: { name: "Croácia", flag: "🇭🇷", fifaRank: 11 },
  GHA: { name: "Gana", flag: "🇬🇭", fifaRank: 73 },
  PAN: { name: "Panamá", flag: "🇵🇦", fifaRank: 34 },
};

const CHANNELS = {
  s1: {
    name: "Sport TV 1",
    abbreviation: "STV1",
    icon: "icons/sporttv1",
    ext: "svg",
  },
  s2: {
    name: "Sport TV 2",
    abbreviation: "STV2",
    icon: "icons/sporttv2",
    ext: "svg",
  },
  s4: {
    name: "Sport TV 4",
    abbreviation: "STV4",
    icon: "icons/sporttv4",
    ext: "svg",
  },
  s5: {
    name: "Sport TV 5",
    abbreviation: "STV5",
    icon: "icons/sporttv5",
    ext: "svg",
  },
  s: {
    name: "Sport TV (canal por anunciar)",
    abbreviation: "STV",
    icon: "icons/sporttv",
    ext: "svg",
  },
  lm: {
    name: "LiveModeTV (YouTube)",
    abbreviation: "LM",
    icon: "icons/livemodetv",
    ext: "svg",
  },
  sic: { name: "SIC", abbreviation: "SIC", icon: "icons/sic", ext: "png" },
  rtp: { name: "RTP 1", abbreviation: "RTP1", icon: "icons/rtp1", ext: "svg" },
  tvi: { name: "TVI", abbreviation: "TVI", icon: "icons/tvi", ext: "png" },
};

/* Venues, from worldcup26.ir/get/stadiums (city names in Portuguese). */
const STADIUMS = {
  1: { name: "Estadio Azteca", city: "Cidade do México" },
  2: { name: "Estadio Akron", city: "Guadalajara" },
  3: { name: "Estadio BBVA", city: "Monterrei" },
  4: { name: "AT&T Stadium", city: "Dallas" },
  5: { name: "NRG Stadium", city: "Houston" },
  6: { name: "GEHA Field at Arrowhead Stadium", city: "Kansas City" },
  7: { name: "Mercedes-Benz Stadium", city: "Atlanta" },
  8: { name: "Hard Rock Stadium", city: "Miami" },
  9: { name: "Gillette Stadium", city: "Boston" },
  10: { name: "Lincoln Financial Field", city: "Filadélfia" },
  11: { name: "MetLife Stadium", city: "Nova Iorque" },
  12: { name: "BMO Field", city: "Toronto" },
  13: { name: "BC Place", city: "Vancouver" },
  14: { name: "Lumen Field", city: "Seattle" },
  15: { name: "Levi's Stadium", city: "Baía de SF" },
  16: { name: "SoFi Stadium", city: "Los Angeles" },
};

/* stadium_id per group match (key = group|home|away), from worldcup26.ir/get/games */
const GROUP_MATCH_STADIUM = {
  "A|MEX|RSA": 1,
  "A|KOR|CZE": 2,
  "B|CAN|BIH": 12,
  "D|USA|PAR": 16,
  "C|HAI|SCO": 9,
  "D|AUS|TUR": 13,
  "C|BRA|MAR": 11,
  "B|QAT|SUI": 15,
  "E|CIV|ECU": 10,
  "E|GER|CUW": 5,
  "F|NED|JPN": 4,
  "F|SWE|TUN": 3,
  "G|IRN|NZL": 16,
  "H|ESP|CPV": 7,
  "G|BEL|EGY": 14,
  "H|KSA|URU": 8,
  "I|FRA|SEN": 11,
  "I|IRQ|NOR": 9,
  "J|ARG|ALG": 6,
  "J|AUT|JOR": 15,
  "K|POR|COD": 5,
  "L|ENG|CRO": 4,
  "K|UZB|COL": 1,
  "L|GHA|PAN": 12,
  "A|MEX|KOR": 2,
  "B|SUI|BIH": 16,
  "B|CAN|QAT": 13,
  "A|CZE|RSA": 7,
  "C|BRA|HAI": 10,
  "C|SCO|MAR": 9,
  "D|USA|AUS": 14,
  "D|TUR|PAR": 15,
  "E|GER|CIV": 12,
  "E|ECU|CUW": 6,
  "F|NED|SWE": 5,
  "F|TUN|JPN": 3,
  "G|BEL|IRN": 16,
  "G|NZL|EGY": 13,
  "H|ESP|KSA": 7,
  "H|URU|CPV": 8,
  "I|FRA|IRQ": 10,
  "I|NOR|SEN": 11,
  "J|ARG|AUT": 4,
  "J|JOR|ALG": 15,
  "K|POR|UZB": 5,
  "L|PAN|CRO": 12,
  "K|COL|COD": 2,
  "L|ENG|GHA": 9,
  "C|SCO|BRA": 8,
  "C|MAR|HAI": 7,
  "A|RSA|KOR": 3,
  "A|CZE|MEX": 1,
  "B|BIH|QAT": 14,
  "B|SUI|CAN": 13,
  "E|CUW|CIV": 10,
  "E|ECU|GER": 11,
  "D|PAR|AUS": 15,
  "D|TUR|USA": 16,
  "F|JPN|SWE": 4,
  "F|TUN|NED": 6,
  "I|SEN|IRQ": 12,
  "I|NOR|FRA": 9,
  "G|EGY|IRN": 14,
  "G|NZL|BEL": 13,
  "H|CPV|KSA": 5,
  "H|URU|ESP": 2,
  "L|PAN|ENG": 11,
  "L|CRO|GHA": 10,
  "J|ALG|AUT": 6,
  "J|JOR|ARG": 4,
  "K|COL|POR": 8,
  "K|COD|UZB": 7,
};

/* Official FIFA match number (1-72) per group match, from worldcup26.ir/get/games */
const GROUP_MATCH_NUMBER = {
  "A|MEX|RSA": 1,
  "A|KOR|CZE": 2,
  "A|CZE|RSA": 28,
  "A|MEX|KOR": 25,
  "A|CZE|MEX": 52,
  "A|RSA|KOR": 51,
  "B|CAN|BIH": 3,
  "B|QAT|SUI": 8,
  "B|SUI|BIH": 26,
  "B|CAN|QAT": 27,
  "B|SUI|CAN": 54,
  "B|BIH|QAT": 53,
  "C|BRA|MAR": 7,
  "C|HAI|SCO": 5,
  "C|SCO|MAR": 30,
  "C|BRA|HAI": 29,
  "C|SCO|BRA": 49,
  "C|MAR|HAI": 50,
  "D|USA|PAR": 4,
  "D|AUS|TUR": 6,
  "D|USA|AUS": 31,
  "D|TUR|PAR": 32,
  "D|TUR|USA": 58,
  "D|PAR|AUS": 57,
  "E|GER|CUW": 10,
  "E|CIV|ECU": 9,
  "E|GER|CIV": 33,
  "E|ECU|CUW": 34,
  "E|CUW|CIV": 55,
  "E|ECU|GER": 56,
  "F|NED|JPN": 11,
  "F|SWE|TUN": 12,
  "F|NED|SWE": 35,
  "F|TUN|JPN": 36,
  "F|JPN|SWE": 59,
  "F|TUN|NED": 60,
  "G|BEL|EGY": 15,
  "G|IRN|NZL": 13,
  "G|BEL|IRN": 37,
  "G|NZL|EGY": 38,
  "G|EGY|IRN": 63,
  "G|NZL|BEL": 64,
  "H|ESP|CPV": 14,
  "H|KSA|URU": 16,
  "H|ESP|KSA": 39,
  "H|URU|CPV": 40,
  "H|CPV|KSA": 65,
  "H|URU|ESP": 66,
  "I|FRA|SEN": 17,
  "I|IRQ|NOR": 18,
  "I|FRA|IRQ": 41,
  "I|NOR|SEN": 42,
  "I|NOR|FRA": 62,
  "I|SEN|IRQ": 61,
  "J|ARG|ALG": 19,
  "J|AUT|JOR": 20,
  "J|ARG|AUT": 43,
  "J|JOR|ALG": 44,
  "J|ALG|AUT": 69,
  "J|JOR|ARG": 70,
  "K|POR|COD": 21,
  "K|UZB|COL": 23,
  "K|POR|UZB": 45,
  "K|COL|COD": 47,
  "K|COL|POR": 71,
  "K|COD|UZB": 72,
  "L|ENG|CRO": 22,
  "L|GHA|PAN": 24,
  "L|ENG|GHA": 48,
  "L|PAN|CRO": 46,
  "L|PAN|ENG": 67,
  "L|CRO|GHA": 68,
};

/* stadium_id per knockout match id */
const KO_MATCH_STADIUM = {
  73: 16,
  74: 9,
  75: 3,
  76: 5,
  77: 11,
  78: 4,
  79: 1,
  80: 7,
  81: 15,
  82: 14,
  83: 12,
  84: 16,
  85: 13,
  86: 8,
  87: 6,
  88: 4,
  89: 10,
  90: 5,
  91: 11,
  92: 1,
  93: 4,
  94: 14,
  95: 7,
  96: 13,
  97: 9,
  98: 16,
  99: 8,
  100: 6,
  101: 4,
  102: 7,
  103: 8,
  104: 11,
};

/* Group-stage fixtures. Times are Portugal Continental (UTC+1). */
const GROUP_LETTERS = "ABCDEFGHIJKL".split("");
const GROUP_FIXTURES = {
  A: [
    {
      home: "MEX",
      away: "RSA",
      date: "11/06",
      time: "20:00",
      channels: ["tvi", "s5", "lm"],
    },
    {
      home: "KOR",
      away: "CZE",
      date: "12/06",
      time: "03:00",
      channels: ["s5"],
    },
    {
      home: "CZE",
      away: "RSA",
      date: "18/06",
      time: "17:00",
      channels: ["s5"],
    },
    {
      home: "MEX",
      away: "KOR",
      date: "19/06",
      time: "02:00",
      channels: ["s5"],
    },
    {
      home: "CZE",
      away: "MEX",
      date: "25/06",
      time: "02:00",
      channels: ["s5"],
    },
    {
      home: "RSA",
      away: "KOR",
      date: "25/06",
      time: "02:00",
      channels: ["s1"],
    },
  ],
  B: [
    {
      home: "CAN",
      away: "BIH",
      date: "12/06",
      time: "20:00",
      channels: ["sic", "s1", "s5", "lm"],
    },
    {
      home: "QAT",
      away: "SUI",
      date: "13/06",
      time: "20:00",
      channels: ["s5"],
    },
    {
      home: "SUI",
      away: "BIH",
      date: "18/06",
      time: "20:00",
      channels: ["rtp", "s1", "s5", "lm"],
    },
    {
      home: "CAN",
      away: "QAT",
      date: "18/06",
      time: "23:00",
      channels: ["s5"],
    },
    {
      home: "SUI",
      away: "CAN",
      date: "24/06",
      time: "20:00",
      channels: ["s5"],
    },
    {
      home: "BIH",
      away: "QAT",
      date: "24/06",
      time: "20:00",
      channels: ["s1"],
    },
  ],
  C: [
    {
      home: "BRA",
      away: "MAR",
      date: "13/06",
      time: "23:00",
      channels: ["s1", "s5", "lm"],
    },
    {
      home: "HAI",
      away: "SCO",
      date: "14/06",
      time: "02:00",
      channels: ["s1"],
    },
    {
      home: "SCO",
      away: "MAR",
      date: "19/06",
      time: "23:00",
      channels: ["s5"],
    },
    {
      home: "BRA",
      away: "HAI",
      date: "20/06",
      time: "01:30",
      channels: ["s1", "s5", "lm"],
    },
    {
      home: "SCO",
      away: "BRA",
      date: "24/06",
      time: "23:00",
      channels: ["s1", "lm"],
    },
    {
      home: "MAR",
      away: "HAI",
      date: "24/06",
      time: "23:00",
      channels: ["s5"],
    },
  ],
  D: [
    {
      home: "USA",
      away: "PAR",
      date: "13/06",
      time: "02:00",
      channels: ["s5"],
    },
    {
      home: "AUS",
      away: "TUR",
      date: "14/06",
      time: "05:00",
      channels: ["s5"],
    },
    {
      home: "USA",
      away: "AUS",
      date: "19/06",
      time: "20:00",
      channels: ["s5"],
    },
    {
      home: "TUR",
      away: "PAR",
      date: "20/06",
      time: "04:00",
      channels: ["s5"],
    },
    {
      home: "TUR",
      away: "USA",
      date: "26/06",
      time: "03:00",
      channels: ["s5"],
    },
    {
      home: "PAR",
      away: "AUS",
      date: "26/06",
      time: "03:00",
      channels: ["s1"],
    },
  ],
  E: [
    {
      home: "GER",
      away: "CUW",
      date: "14/06",
      time: "18:00",
      channels: ["s1", "s5", "lm"],
    },
    {
      home: "CIV",
      away: "ECU",
      date: "15/06",
      time: "00:00",
      channels: ["s5"],
    },
    {
      home: "GER",
      away: "CIV",
      date: "20/06",
      time: "21:00",
      channels: ["tvi", "s1", "s5", "lm"],
    },
    {
      home: "ECU",
      away: "CUW",
      date: "21/06",
      time: "01:00",
      channels: ["s5"],
    },
    {
      home: "CUW",
      away: "CIV",
      date: "25/06",
      time: "21:00",
      channels: ["s5"],
    },
    {
      home: "ECU",
      away: "GER",
      date: "25/06",
      time: "21:00",
      channels: ["sic", "s1", "lm"],
    },
  ],
  F: [
    {
      home: "NED",
      away: "JPN",
      date: "14/06",
      time: "21:00",
      channels: ["s5"],
    },
    {
      home: "SWE",
      away: "TUN",
      date: "15/06",
      time: "03:00",
      channels: ["s5"],
    },
    {
      home: "NED",
      away: "SWE",
      date: "20/06",
      time: "18:00",
      channels: ["s5"],
    },
    {
      home: "TUN",
      away: "JPN",
      date: "21/06",
      time: "05:00",
      channels: ["s5"],
    },
    {
      home: "JPN",
      away: "SWE",
      date: "26/06",
      time: "00:00",
      channels: ["s5"],
    },
    {
      home: "TUN",
      away: "NED",
      date: "26/06",
      time: "00:00",
      channels: ["s1"],
    },
  ],
  G: [
    {
      home: "BEL",
      away: "EGY",
      date: "15/06",
      time: "20:00",
      channels: ["s5"],
    },
    {
      home: "IRN",
      away: "NZL",
      date: "16/06",
      time: "02:00",
      channels: ["s5"],
    },
    {
      home: "BEL",
      away: "IRN",
      date: "21/06",
      time: "20:00",
      channels: ["s5"],
    },
    {
      home: "NZL",
      away: "EGY",
      date: "22/06",
      time: "02:00",
      channels: ["s5"],
    },
    {
      home: "EGY",
      away: "IRN",
      date: "27/06",
      time: "04:00",
      channels: ["s1"],
    },
    {
      home: "NZL",
      away: "BEL",
      date: "27/06",
      time: "04:00",
      channels: ["s5"],
    },
  ],
  H: [
    {
      home: "ESP",
      away: "CPV",
      date: "15/06",
      time: "17:00",
      channels: ["s5", "lm"],
    },
    {
      home: "KSA",
      away: "URU",
      date: "15/06",
      time: "23:00",
      channels: ["s5"],
    },
    {
      home: "ESP",
      away: "KSA",
      date: "21/06",
      time: "17:00",
      channels: ["s1", "s5", "lm"],
    },
    {
      home: "URU",
      away: "CPV",
      date: "21/06",
      time: "23:00",
      channels: ["s5"],
    },
    {
      home: "CPV",
      away: "KSA",
      date: "27/06",
      time: "01:00",
      channels: ["s1"],
    },
    {
      home: "URU",
      away: "ESP",
      date: "27/06",
      time: "01:00",
      channels: ["s5"],
    },
  ],
  I: [
    {
      home: "FRA",
      away: "SEN",
      date: "16/06",
      time: "20:00",
      channels: ["rtp", "s1", "s5", "lm"],
    },
    {
      home: "IRQ",
      away: "NOR",
      date: "16/06",
      time: "23:00",
      channels: ["s5"],
    },
    {
      home: "FRA",
      away: "IRQ",
      date: "22/06",
      time: "22:00",
      channels: ["s5"],
    },
    {
      home: "NOR",
      away: "SEN",
      date: "23/06",
      time: "01:00",
      channels: ["s5"],
    },
    {
      home: "NOR",
      away: "FRA",
      date: "26/06",
      time: "20:00",
      channels: ["tvi", "s1", "lm"],
    },
    {
      home: "SEN",
      away: "IRQ",
      date: "26/06",
      time: "20:00",
      channels: ["s5"],
    },
  ],
  J: [
    {
      home: "ARG",
      away: "ALG",
      date: "17/06",
      time: "02:00",
      channels: ["s5"],
    },
    {
      home: "AUT",
      away: "JOR",
      date: "17/06",
      time: "05:00",
      channels: ["s5"],
    },
    {
      home: "ARG",
      away: "AUT",
      date: "22/06",
      time: "18:00",
      channels: ["s1", "s5", "lm"],
    },
    {
      home: "JOR",
      away: "ALG",
      date: "23/06",
      time: "04:00",
      channels: ["s5"],
    },
    {
      home: "ALG",
      away: "AUT",
      date: "28/06",
      time: "03:00",
      channels: ["s4"],
    },
    {
      home: "JOR",
      away: "ARG",
      date: "28/06",
      time: "03:00",
      channels: ["s5"],
    },
  ],
  K: [
    {
      home: "POR",
      away: "COD",
      date: "17/06",
      time: "18:00",
      channels: ["sic", "s1", "s5", "lm"],
    },
    {
      home: "UZB",
      away: "COL",
      date: "18/06",
      time: "03:00",
      channels: ["s5"],
    },
    {
      home: "POR",
      away: "UZB",
      date: "23/06",
      time: "18:00",
      channels: ["tvi", "s1", "s5", "lm"],
    },
    {
      home: "COL",
      away: "COD",
      date: "24/06",
      time: "03:00",
      channels: ["s5"],
    },
    {
      home: "COL",
      away: "POR",
      date: "28/06",
      time: "00:30",
      channels: ["rtp", "s1", "lm"],
    },
    {
      home: "COD",
      away: "UZB",
      date: "28/06",
      time: "00:30",
      channels: ["s5"],
    },
  ],
  L: [
    {
      home: "ENG",
      away: "CRO",
      date: "17/06",
      time: "21:00",
      channels: ["s5"],
    },
    {
      home: "GHA",
      away: "PAN",
      date: "18/06",
      time: "00:00",
      channels: ["s5"],
    },
    {
      home: "ENG",
      away: "GHA",
      date: "23/06",
      time: "21:00",
      channels: ["s5"],
    },
    {
      home: "PAN",
      away: "CRO",
      date: "24/06",
      time: "00:00",
      channels: ["s5"],
    },
    {
      home: "PAN",
      away: "ENG",
      date: "27/06",
      time: "22:00",
      channels: ["s5"],
    },
    {
      home: "CRO",
      away: "GHA",
      date: "27/06",
      time: "22:00",
      channels: ["s2"],
    },
  ],
};

/* Final group-stage results, baked in now that the group stage is over, so the
   score boxes show static numbers instead of editable inputs. Keyed like the old
   user input: groupLetter + fixtureIndex (0-5) -> [homeGoals, awayGoals]. */
const GROUP_RESULTS = {
  A0: [2, 0],
  A1: [2, 1],
  A2: [1, 1],
  A3: [1, 0],
  A4: [0, 3],
  A5: [1, 0],
  B0: [1, 1],
  B1: [1, 1],
  B2: [4, 1],
  B3: [6, 0],
  B4: [2, 1],
  B5: [3, 1],
  C0: [1, 1],
  C1: [0, 1],
  C2: [0, 1],
  C3: [3, 0],
  C4: [0, 3],
  C5: [4, 2],
  D0: [4, 1],
  D1: [2, 0],
  D2: [2, 0],
  D3: [0, 1],
  D4: [3, 2],
  D5: [0, 0],
  E0: [7, 1],
  E1: [1, 0],
  E2: [2, 1],
  E3: [0, 0],
  E4: [0, 2],
  E5: [2, 1],
  F0: [2, 2],
  F1: [5, 1],
  F2: [5, 1],
  F3: [0, 4],
  F4: [1, 1],
  F5: [1, 3],
  G0: [1, 1],
  G1: [2, 2],
  G2: [0, 0],
  G3: [1, 3],
  G4: [1, 1],
  G5: [1, 5],
  H0: [0, 0],
  H1: [1, 1],
  H2: [4, 0],
  H3: [2, 2],
  H4: [0, 0],
  H5: [0, 1],
  I0: [3, 1],
  I1: [1, 4],
  I2: [3, 0],
  I3: [3, 2],
  I4: [1, 4],
  I5: [5, 0],
  J0: [3, 0],
  J1: [3, 1],
  J2: [2, 0],
  J3: [1, 2],
  J4: [3, 3],
  J5: [1, 3],
  K0: [1, 1],
  K1: [1, 3],
  K2: [5, 0],
  K3: [1, 0],
  K4: [0, 0],
  K5: [3, 1],
  L0: [4, 2],
  L1: [1, 0],
  L2: [0, 0],
  L3: [0, 1],
  L4: [0, 2],
  L5: [2, 1],
};
/* Disciplinary record per team, used only for the FIFA "fair play" tie-break
   (yellow, double-yellow, direct-red counts). The live API does not provide it,
   so fill these in by hand here. Conduct score = -1 per yellow, -3 per double
   yellow, -4 per direct red; higher (closer to 0) is better. Order follows each
   group; leave [0, 0, 0] for teams with no relevant cards. */
const GROUP_CARDS = {
  // Grupo A
  MEX: [2, 0, 1],
  RSA: [5, 0, 2],
  KOR: [4, 0, 0],
  CZE: [1, 0, 0],
  // Grupo B
  CAN: [5, 0, 0],
  BIH: [6, 0, 1],
  QAT: [4, 0, 2],
  SUI: [3, 0, 0],
  // Grupo C
  BRA: [5, 0, 0],
  MAR: [1, 0, 0],
  HAI: [7, 0, 0],
  SCO: [5, 0, 0],
  // Grupo D
  USA: [5, 0, 0],
  PAR: [7, 0, 1],
  AUS: [5, 0, 0],
  TUR: [3, 0, 0],
  // Grupo E
  GER: [1, 0, 0],
  CUW: [7, 0, 0],
  CIV: [4, 0, 0],
  ECU: [5, 0, 0],
  // Grupo F
  NED: [3, 0, 0],
  JPN: [1, 0, 0],
  SWE: [5, 0, 0],
  TUN: [1, 0, 0],
  // Grupo G
  BEL: [3, 0, 1],
  EGY: [6, 0, 0],
  IRN: [6, 0, 0],
  NZL: [4, 0, 0],
  // Grupo H
  ESP: [2, 0, 0],
  CPV: [4, 0, 0],
  KSA: [5, 0, 0],
  URU: [5, 0, 1],
  // Grupo I
  FRA: [1, 0, 0],
  SEN: [2, 0, 0],
  IRQ: [4, 0, 1],
  NOR: [1, 0, 0],
  // Grupo J
  ARG: [2, 0, 0],
  ALG: [1, 0, 0],
  AUT: [4, 0, 0],
  JOR: [4, 0, 0],
  // Grupo K
  POR: [4, 0, 0],
  COD: [5, 0, 0],
  UZB: [4, 0, 0],
  COL: [4, 0, 0],
  // Grupo L
  ENG: [2, 0, 0],
  CRO: [2, 0, 0],
  GHA: [3, 0, 0],
  PAN: [5, 0, 0],
};

/* FIFA Annex C: all 495 combinations of the 8 groups that supply the
	 qualified third-placed teams. Key = those 8 group letters, sorted.
	 Value = which group's third goes to each slot, in the order
	 [Match 79, 85, 81, 74, 82, 77, 87, 80] (i.e. vs winners of A,B,D,E,G,I,K,L). */
const THIRD_PLACE_MATCH_ORDER = [79, 85, 81, 74, 82, 77, 87, 80];
const THIRD_PLACE_BRACKET_MAP = {
  EFGHIJKL: "EJIFHGLK",
  DFGHIJKL: "HGIDJFLK",
  DEGHIJKL: "EJIDHGLK",
  DEFHIJKL: "EJIDHFLK",
  DEFGIJKL: "EGIDJFLK",
  DEFGHJKL: "EGJDHFLK",
  DEFGHIKL: "EGIDHFLK",
  DEFGHIJL: "EGJDHFLI",
  DEFGHIJK: "EGJDHFIK",
  CFGHIJKL: "HGICJFLK",
  CEGHIJKL: "EJICHGLK",
  CEFHIJKL: "EJICHFLK",
  CEFGIJKL: "EGICJFLK",
  CEFGHJKL: "EGJCHFLK",
  CEFGHIKL: "EGICHFLK",
  CEFGHIJL: "EGJCHFLI",
  CEFGHIJK: "EGJCHFIK",
  CDGHIJKL: "HGICJDLK",
  CDFHIJKL: "CJIDHFLK",
  CDFGIJKL: "CGIDJFLK",
  CDFGHJKL: "CGJDHFLK",
  CDFGHIKL: "CGIDHFLK",
  CDFGHIJL: "CGJDHFLI",
  CDFGHIJK: "CGJDHFIK",
  CDEHIJKL: "EJICHDLK",
  CDEGIJKL: "EGICJDLK",
  CDEGHJKL: "EGJCHDLK",
  CDEGHIKL: "EGICHDLK",
  CDEGHIJL: "EGJCHDLI",
  CDEGHIJK: "EGJCHDIK",
  CDEFIJKL: "CJEDIFLK",
  CDEFHJKL: "CJEDHFLK",
  CDEFHIKL: "CEIDHFLK",
  CDEFHIJL: "CJEDHFLI",
  CDEFHIJK: "CJEDHFIK",
  CDEFGJKL: "CGEDJFLK",
  CDEFGIKL: "CGEDIFLK",
  CDEFGIJL: "CGEDJFLI",
  CDEFGIJK: "CGEDJFIK",
  CDEFGHKL: "CGEDHFLK",
  CDEFGHJL: "CGJDHFLE",
  CDEFGHJK: "CGJDHFEK",
  CDEFGHIL: "CGEDHFLI",
  CDEFGHIK: "CGEDHFIK",
  CDEFGHIJ: "CGJDHFEI",
  BFGHIJKL: "HJBFIGLK",
  BEGHIJKL: "EJIBHGLK",
  BEFHIJKL: "EJBFIHLK",
  BEFGIJKL: "EJBFIGLK",
  BEFGHJKL: "EJBFHGLK",
  BEFGHIKL: "EGBFIHLK",
  BEFGHIJL: "EJBFHGLI",
  BEFGHIJK: "EJBFHGIK",
  BDGHIJKL: "HJBDIGLK",
  BDFHIJKL: "HJBDIFLK",
  BDFGIJKL: "IGBDJFLK",
  BDFGHJKL: "HGBDJFLK",
  BDFGHIKL: "HGBDIFLK",
  BDFGHIJL: "HGBDJFLI",
  BDFGHIJK: "HGBDJFIK",
  BDEHIJKL: "EJBDIHLK",
  BDEGIJKL: "EJBDIGLK",
  BDEGHJKL: "EJBDHGLK",
  BDEGHIKL: "EGBDIHLK",
  BDEGHIJL: "EJBDHGLI",
  BDEGHIJK: "EJBDHGIK",
  BDEFIJKL: "EJBDIFLK",
  BDEFHJKL: "EJBDHFLK",
  BDEFHIKL: "EIBDHFLK",
  BDEFHIJL: "EJBDHFLI",
  BDEFHIJK: "EJBDHFIK",
  BDEFGJKL: "EGBDJFLK",
  BDEFGIKL: "EGBDIFLK",
  BDEFGIJL: "EGBDJFLI",
  BDEFGIJK: "EGBDJFIK",
  BDEFGHKL: "EGBDHFLK",
  BDEFGHJL: "HGBDJFLE",
  BDEFGHJK: "HGBDJFEK",
  BDEFGHIL: "EGBDHFLI",
  BDEFGHIK: "EGBDHFIK",
  BDEFGHIJ: "HGBDJFEI",
  BCGHIJKL: "HJBCIGLK",
  BCFHIJKL: "HJBCIFLK",
  BCFGIJKL: "IGBCJFLK",
  BCFGHJKL: "HGBCJFLK",
  BCFGHIKL: "HGBCIFLK",
  BCFGHIJL: "HGBCJFLI",
  BCFGHIJK: "HGBCJFIK",
  BCEHIJKL: "EJBCIHLK",
  BCEGIJKL: "EJBCIGLK",
  BCEGHJKL: "EJBCHGLK",
  BCEGHIKL: "EGBCIHLK",
  BCEGHIJL: "EJBCHGLI",
  BCEGHIJK: "EJBCHGIK",
  BCEFIJKL: "EJBCIFLK",
  BCEFHJKL: "EJBCHFLK",
  BCEFHIKL: "EIBCHFLK",
  BCEFHIJL: "EJBCHFLI",
  BCEFHIJK: "EJBCHFIK",
  BCEFGJKL: "EGBCJFLK",
  BCEFGIKL: "EGBCIFLK",
  BCEFGIJL: "EGBCJFLI",
  BCEFGIJK: "EGBCJFIK",
  BCEFGHKL: "EGBCHFLK",
  BCEFGHJL: "HGBCJFLE",
  BCEFGHJK: "HGBCJFEK",
  BCEFGHIL: "EGBCHFLI",
  BCEFGHIK: "EGBCHFIK",
  BCEFGHIJ: "HGBCJFEI",
  BCDHIJKL: "HJBCIDLK",
  BCDGIJKL: "IGBCJDLK",
  BCDGHJKL: "HGBCJDLK",
  BCDGHIKL: "HGBCIDLK",
  BCDGHIJL: "HGBCJDLI",
  BCDGHIJK: "HGBCJDIK",
  BCDFIJKL: "CJBDIFLK",
  BCDFHJKL: "CJBDHFLK",
  BCDFHIKL: "CIBDHFLK",
  BCDFHIJL: "CJBDHFLI",
  BCDFHIJK: "CJBDHFIK",
  BCDFGJKL: "CGBDJFLK",
  BCDFGIKL: "CGBDIFLK",
  BCDFGIJL: "CGBDJFLI",
  BCDFGIJK: "CGBDJFIK",
  BCDFGHKL: "CGBDHFLK",
  BCDFGHJL: "CGBDHFLJ",
  BCDFGHJK: "HGBCJFDK",
  BCDFGHIL: "CGBDHFLI",
  BCDFGHIK: "CGBDHFIK",
  BCDFGHIJ: "HGBCJFDI",
  BCDEIJKL: "EJBCIDLK",
  BCDEHJKL: "EJBCHDLK",
  BCDEHIKL: "EIBCHDLK",
  BCDEHIJL: "EJBCHDLI",
  BCDEHIJK: "EJBCHDIK",
  BCDEGJKL: "EGBCJDLK",
  BCDEGIKL: "EGBCIDLK",
  BCDEGIJL: "EGBCJDLI",
  BCDEGIJK: "EGBCJDIK",
  BCDEGHKL: "EGBCHDLK",
  BCDEGHJL: "HGBCJDLE",
  BCDEGHJK: "HGBCJDEK",
  BCDEGHIL: "EGBCHDLI",
  BCDEGHIK: "EGBCHDIK",
  BCDEGHIJ: "HGBCJDEI",
  BCDEFJKL: "CJBDEFLK",
  BCDEFIKL: "CEBDIFLK",
  BCDEFIJL: "CJBDEFLI",
  BCDEFIJK: "CJBDEFIK",
  BCDEFHKL: "CEBDHFLK",
  BCDEFHJL: "CJBDHFLE",
  BCDEFHJK: "CJBDHFEK",
  BCDEFHIL: "CEBDHFLI",
  BCDEFHIK: "CEBDHFIK",
  BCDEFHIJ: "CJBDHFEI",
  BCDEFGKL: "CGBDEFLK",
  BCDEFGJL: "CGBDJFLE",
  BCDEFGJK: "CGBDJFEK",
  BCDEFGIL: "CGBDEFLI",
  BCDEFGIK: "CGBDEFIK",
  BCDEFGIJ: "CGBDJFEI",
  BCDEFGHL: "CGBDHFLE",
  BCDEFGHK: "CGBDHFEK",
  BCDEFGHJ: "HGBCJFDE",
  BCDEFGHI: "CGBDHFEI",
  AFGHIJKL: "HJIFAGLK",
  AEGHIJKL: "EJIAHGLK",
  AEFHIJKL: "EJIFAHLK",
  AEFGIJKL: "EJIFAGLK",
  AEFGHJKL: "EGJFAHLK",
  AEFGHIKL: "EGIFAHLK",
  AEFGHIJL: "EGJFAHLI",
  AEFGHIJK: "EGJFAHIK",
  ADGHIJKL: "HJIDAGLK",
  ADFHIJKL: "HJIDAFLK",
  ADFGIJKL: "IGJDAFLK",
  ADFGHJKL: "HGJDAFLK",
  ADFGHIKL: "HGIDAFLK",
  ADFGHIJL: "HGJDAFLI",
  ADFGHIJK: "HGJDAFIK",
  ADEHIJKL: "EJIDAHLK",
  ADEGIJKL: "EJIDAGLK",
  ADEGHJKL: "EGJDAHLK",
  ADEGHIKL: "EGIDAHLK",
  ADEGHIJL: "EGJDAHLI",
  ADEGHIJK: "EGJDAHIK",
  ADEFIJKL: "EJIDAFLK",
  ADEFHJKL: "HJEDAFLK",
  ADEFHIKL: "HEIDAFLK",
  ADEFHIJL: "HJEDAFLI",
  ADEFHIJK: "HJEDAFIK",
  ADEFGJKL: "EGJDAFLK",
  ADEFGIKL: "EGIDAFLK",
  ADEFGIJL: "EGJDAFLI",
  ADEFGIJK: "EGJDAFIK",
  ADEFGHKL: "HGEDAFLK",
  ADEFGHJL: "HGJDAFLE",
  ADEFGHJK: "HGJDAFEK",
  ADEFGHIL: "HGEDAFLI",
  ADEFGHIK: "HGEDAFIK",
  ADEFGHIJ: "HGJDAFEI",
  ACGHIJKL: "HJICAGLK",
  ACFHIJKL: "HJICAFLK",
  ACFGIJKL: "IGJCAFLK",
  ACFGHJKL: "HGJCAFLK",
  ACFGHIKL: "HGICAFLK",
  ACFGHIJL: "HGJCAFLI",
  ACFGHIJK: "HGJCAFIK",
  ACEHIJKL: "EJICAHLK",
  ACEGIJKL: "EJICAGLK",
  ACEGHJKL: "EGJCAHLK",
  ACEGHIKL: "EGICAHLK",
  ACEGHIJL: "EGJCAHLI",
  ACEGHIJK: "EGJCAHIK",
  ACEFIJKL: "EJICAFLK",
  ACEFHJKL: "HJECAFLK",
  ACEFHIKL: "HEICAFLK",
  ACEFHIJL: "HJECAFLI",
  ACEFHIJK: "HJECAFIK",
  ACEFGJKL: "EGJCAFLK",
  ACEFGIKL: "EGICAFLK",
  ACEFGIJL: "EGJCAFLI",
  ACEFGIJK: "EGJCAFIK",
  ACEFGHKL: "HGECAFLK",
  ACEFGHJL: "HGJCAFLE",
  ACEFGHJK: "HGJCAFEK",
  ACEFGHIL: "HGECAFLI",
  ACEFGHIK: "HGECAFIK",
  ACEFGHIJ: "HGJCAFEI",
  ACDHIJKL: "HJICADLK",
  ACDGIJKL: "IGJCADLK",
  ACDGHJKL: "HGJCADLK",
  ACDGHIKL: "HGICADLK",
  ACDGHIJL: "HGJCADLI",
  ACDGHIJK: "HGJCADIK",
  ACDFIJKL: "CJIDAFLK",
  ACDFHJKL: "HJFCADLK",
  ACDFHIKL: "HFICADLK",
  ACDFHIJL: "HJFCADLI",
  ACDFHIJK: "HJFCADIK",
  ACDFGJKL: "CGJDAFLK",
  ACDFGIKL: "CGIDAFLK",
  ACDFGIJL: "CGJDAFLI",
  ACDFGIJK: "CGJDAFIK",
  ACDFGHKL: "HGFCADLK",
  ACDFGHJL: "CGJDAFLH",
  ACDFGHJK: "HGJCAFDK",
  ACDFGHIL: "HGFCADLI",
  ACDFGHIK: "HGFCADIK",
  ACDFGHIJ: "HGJCAFDI",
  ACDEIJKL: "EJICADLK",
  ACDEHJKL: "HJECADLK",
  ACDEHIKL: "HEICADLK",
  ACDEHIJL: "HJECADLI",
  ACDEHIJK: "HJECADIK",
  ACDEGJKL: "EGJCADLK",
  ACDEGIKL: "EGICADLK",
  ACDEGIJL: "EGJCADLI",
  ACDEGIJK: "EGJCADIK",
  ACDEGHKL: "HGECADLK",
  ACDEGHJL: "HGJCADLE",
  ACDEGHJK: "HGJCADEK",
  ACDEGHIL: "HGECADLI",
  ACDEGHIK: "HGECADIK",
  ACDEGHIJ: "HGJCADEI",
  ACDEFJKL: "CJEDAFLK",
  ACDEFIKL: "CEIDAFLK",
  ACDEFIJL: "CJEDAFLI",
  ACDEFIJK: "CJEDAFIK",
  ACDEFHKL: "HEFCADLK",
  ACDEFHJL: "HJFCADLE",
  ACDEFHJK: "HJECAFDK",
  ACDEFHIL: "HEFCADLI",
  ACDEFHIK: "HEFCADIK",
  ACDEFHIJ: "HJECAFDI",
  ACDEFGKL: "CGEDAFLK",
  ACDEFGJL: "CGJDAFLE",
  ACDEFGJK: "CGJDAFEK",
  ACDEFGIL: "CGEDAFLI",
  ACDEFGIK: "CGEDAFIK",
  ACDEFGIJ: "CGJDAFEI",
  ACDEFGHL: "HGFCADLE",
  ACDEFGHK: "HGECAFDK",
  ACDEFGHJ: "HGJCAFDE",
  ACDEFGHI: "HGECAFDI",
  ABGHIJKL: "HJBAIGLK",
  ABFHIJKL: "HJBAIFLK",
  ABFGIJKL: "IJBFAGLK",
  ABFGHJKL: "HJBFAGLK",
  ABFGHIKL: "HGBAIFLK",
  ABFGHIJL: "HJBFAGLI",
  ABFGHIJK: "HJBFAGIK",
  ABEHIJKL: "EJBAIHLK",
  ABEGIJKL: "EJBAIGLK",
  ABEGHJKL: "EJBAHGLK",
  ABEGHIKL: "EGBAIHLK",
  ABEGHIJL: "EJBAHGLI",
  ABEGHIJK: "EJBAHGIK",
  ABEFIJKL: "EJBAIFLK",
  ABEFHJKL: "EJBFAHLK",
  ABEFHIKL: "EIBFAHLK",
  ABEFHIJL: "EJBFAHLI",
  ABEFHIJK: "EJBFAHIK",
  ABEFGJKL: "EJBFAGLK",
  ABEFGIKL: "EGBAIFLK",
  ABEFGIJL: "EJBFAGLI",
  ABEFGIJK: "EJBFAGIK",
  ABEFGHKL: "EGBFAHLK",
  ABEFGHJL: "HJBFAGLE",
  ABEFGHJK: "HJBFAGEK",
  ABEFGHIL: "EGBFAHLI",
  ABEFGHIK: "EGBFAHIK",
  ABEFGHIJ: "HJBFAGEI",
  ABDHIJKL: "IJBDAHLK",
  ABDGIJKL: "IJBDAGLK",
  ABDGHJKL: "HJBDAGLK",
  ABDGHIKL: "IGBDAHLK",
  ABDGHIJL: "HJBDAGLI",
  ABDGHIJK: "HJBDAGIK",
  ABDFIJKL: "IJBDAFLK",
  ABDFHJKL: "HJBDAFLK",
  ABDFHIKL: "HIBDAFLK",
  ABDFHIJL: "HJBDAFLI",
  ABDFHIJK: "HJBDAFIK",
  ABDFGJKL: "FJBDAGLK",
  ABDFGIKL: "IGBDAFLK",
  ABDFGIJL: "FJBDAGLI",
  ABDFGIJK: "FJBDAGIK",
  ABDFGHKL: "HGBDAFLK",
  ABDFGHJL: "HGBDAFLJ",
  ABDFGHJK: "HGBDAFJK",
  ABDFGHIL: "HGBDAFLI",
  ABDFGHIK: "HGBDAFIK",
  ABDFGHIJ: "HGBDAFIJ",
  ABDEIJKL: "EJBAIDLK",
  ABDEHJKL: "EJBDAHLK",
  ABDEHIKL: "EIBDAHLK",
  ABDEHIJL: "EJBDAHLI",
  ABDEHIJK: "EJBDAHIK",
  ABDEGJKL: "EJBDAGLK",
  ABDEGIKL: "EGBAIDLK",
  ABDEGIJL: "EJBDAGLI",
  ABDEGIJK: "EJBDAGIK",
  ABDEGHKL: "EGBDAHLK",
  ABDEGHJL: "HJBDAGLE",
  ABDEGHJK: "HJBDAGEK",
  ABDEGHIL: "EGBDAHLI",
  ABDEGHIK: "EGBDAHIK",
  ABDEGHIJ: "HJBDAGEI",
  ABDEFJKL: "EJBDAFLK",
  ABDEFIKL: "EIBDAFLK",
  ABDEFIJL: "EJBDAFLI",
  ABDEFIJK: "EJBDAFIK",
  ABDEFHKL: "HEBDAFLK",
  ABDEFHJL: "HJBDAFLE",
  ABDEFHJK: "HJBDAFEK",
  ABDEFHIL: "HEBDAFLI",
  ABDEFHIK: "HEBDAFIK",
  ABDEFHIJ: "HJBDAFEI",
  ABDEFGKL: "EGBDAFLK",
  ABDEFGJL: "EGBDAFLJ",
  ABDEFGJK: "EGBDAFJK",
  ABDEFGIL: "EGBDAFLI",
  ABDEFGIK: "EGBDAFIK",
  ABDEFGIJ: "EGBDAFIJ",
  ABDEFGHL: "HGBDAFLE",
  ABDEFGHK: "HGBDAFEK",
  ABDEFGHJ: "HGBDAFEJ",
  ABDEFGHI: "HGBDAFEI",
  ABCHIJKL: "IJBCAHLK",
  ABCGIJKL: "IJBCAGLK",
  ABCGHJKL: "HJBCAGLK",
  ABCGHIKL: "IGBCAHLK",
  ABCGHIJL: "HJBCAGLI",
  ABCGHIJK: "HJBCAGIK",
  ABCFIJKL: "IJBCAFLK",
  ABCFHJKL: "HJBCAFLK",
  ABCFHIKL: "HIBCAFLK",
  ABCFHIJL: "HJBCAFLI",
  ABCFHIJK: "HJBCAFIK",
  ABCFGJKL: "CJBFAGLK",
  ABCFGIKL: "IGBCAFLK",
  ABCFGIJL: "CJBFAGLI",
  ABCFGIJK: "CJBFAGIK",
  ABCFGHKL: "HGBCAFLK",
  ABCFGHJL: "HGBCAFLJ",
  ABCFGHJK: "HGBCAFJK",
  ABCFGHIL: "HGBCAFLI",
  ABCFGHIK: "HGBCAFIK",
  ABCFGHIJ: "HGBCAFIJ",
  ABCEIJKL: "EJBAICLK",
  ABCEHJKL: "EJBCAHLK",
  ABCEHIKL: "EIBCAHLK",
  ABCEHIJL: "EJBCAHLI",
  ABCEHIJK: "EJBCAHIK",
  ABCEGJKL: "EJBCAGLK",
  ABCEGIKL: "EGBAICLK",
  ABCEGIJL: "EJBCAGLI",
  ABCEGIJK: "EJBCAGIK",
  ABCEGHKL: "EGBCAHLK",
  ABCEGHJL: "HJBCAGLE",
  ABCEGHJK: "HJBCAGEK",
  ABCEGHIL: "EGBCAHLI",
  ABCEGHIK: "EGBCAHIK",
  ABCEGHIJ: "HJBCAGEI",
  ABCEFJKL: "EJBCAFLK",
  ABCEFIKL: "EIBCAFLK",
  ABCEFIJL: "EJBCAFLI",
  ABCEFIJK: "EJBCAFIK",
  ABCEFHKL: "HEBCAFLK",
  ABCEFHJL: "HJBCAFLE",
  ABCEFHJK: "HJBCAFEK",
  ABCEFHIL: "HEBCAFLI",
  ABCEFHIK: "HEBCAFIK",
  ABCEFHIJ: "HJBCAFEI",
  ABCEFGKL: "EGBCAFLK",
  ABCEFGJL: "EGBCAFLJ",
  ABCEFGJK: "EGBCAFJK",
  ABCEFGIL: "EGBCAFLI",
  ABCEFGIK: "EGBCAFIK",
  ABCEFGIJ: "EGBCAFIJ",
  ABCEFGHL: "HGBCAFLE",
  ABCEFGHK: "HGBCAFEK",
  ABCEFGHJ: "HGBCAFEJ",
  ABCEFGHI: "HGBCAFEI",
  ABCDIJKL: "IJBCADLK",
  ABCDHJKL: "HJBCADLK",
  ABCDHIKL: "HIBCADLK",
  ABCDHIJL: "HJBCADLI",
  ABCDHIJK: "HJBCADIK",
  ABCDGJKL: "CJBDAGLK",
  ABCDGIKL: "IGBCADLK",
  ABCDGIJL: "CJBDAGLI",
  ABCDGIJK: "CJBDAGIK",
  ABCDGHKL: "HGBCADLK",
  ABCDGHJL: "HGBCADLJ",
  ABCDGHJK: "HGBCADJK",
  ABCDGHIL: "HGBCADLI",
  ABCDGHIK: "HGBCADIK",
  ABCDGHIJ: "HGBCADIJ",
  ABCDFJKL: "CJBDAFLK",
  ABCDFIKL: "CIBDAFLK",
  ABCDFIJL: "CJBDAFLI",
  ABCDFIJK: "CJBDAFIK",
  ABCDFHKL: "HFBCADLK",
  ABCDFHJL: "CJBDAFLH",
  ABCDFHJK: "HJBCAFDK",
  ABCDFHIL: "HFBCADLI",
  ABCDFHIK: "HFBCADIK",
  ABCDFHIJ: "HJBCAFDI",
  ABCDFGKL: "CGBDAFLK",
  ABCDFGJL: "CGBDAFLJ",
  ABCDFGJK: "CGBDAFJK",
  ABCDFGIL: "CGBDAFLI",
  ABCDFGIK: "CGBDAFIK",
  ABCDFGIJ: "CGBDAFIJ",
  ABCDFGHL: "CGBDAFLH",
  ABCDFGHK: "HGBCAFDK",
  ABCDFGHJ: "HGBCAFDJ",
  ABCDFGHI: "HGBCAFDI",
  ABCDEJKL: "EJBCADLK",
  ABCDEIKL: "EIBCADLK",
  ABCDEIJL: "EJBCADLI",
  ABCDEIJK: "EJBCADIK",
  ABCDEHKL: "HEBCADLK",
  ABCDEHJL: "HJBCADLE",
  ABCDEHJK: "HJBCADEK",
  ABCDEHIL: "HEBCADLI",
  ABCDEHIK: "HEBCADIK",
  ABCDEHIJ: "HJBCADEI",
  ABCDEGKL: "EGBCADLK",
  ABCDEGJL: "EGBCADLJ",
  ABCDEGJK: "EGBCADJK",
  ABCDEGIL: "EGBCADLI",
  ABCDEGIK: "EGBCADIK",
  ABCDEGIJ: "EGBCADIJ",
  ABCDEGHL: "HGBCADLE",
  ABCDEGHK: "HGBCADEK",
  ABCDEGHJ: "HGBCADEJ",
  ABCDEGHI: "HGBCADEI",
  ABCDEFKL: "CEBDAFLK",
  ABCDEFJL: "CJBDAFLE",
  ABCDEFJK: "CJBDAFEK",
  ABCDEFIL: "CEBDAFLI",
  ABCDEFIK: "CEBDAFIK",
  ABCDEFIJ: "CJBDAFEI",
  ABCDEFHL: "HFBCADLE",
  ABCDEFHK: "HEBCAFDK",
  ABCDEFHJ: "HJBCAFDE",
  ABCDEFHI: "HEBCAFDI",
  ABCDEFGL: "CGBDAFLE",
  ABCDEFGK: "CGBDAFEK",
  ABCDEFGJ: "CGBDAFEJ",
  ABCDEFGI: "CGBDAFEI",
  ABCDEFGH: "HGBCAFDE",
};

/* Knockout matches. Slot tokens:
	 "1A"/"2A" = winner / runner-up of group A
	 "T79"     = best third-placed team allocated to match 79 (per Annex C)
	 "W73"/"L101" = winner / loser of an earlier match
	 "when" = date · Portugal time (UTC+1) · venue. */
const KNOCKOUT_MATCHES = [
  {
    id: 73,
    slots: ["2A", "2B"],
    when: "28/06 · 20:00 · Los Angeles",
    channels: ["s1", "s5", "lm"],
  },
  {
    id: 74,
    slots: ["1E", "T74"],
    when: "29/06 · 21:30 · Boston",
    thirdFromGroups: "A/B/C/D/F",
    channels: ["s5"],
  },
  {
    id: 75,
    slots: ["1F", "2C"],
    when: "30/06 · 02:00 · Monterrei",
    channels: ["s5"],
  },
  {
    id: 76,
    slots: ["1C", "2F"],
    when: "29/06 · 18:00 · Houston",
    channels: ["s5", "lm"],
  },
  {
    id: 77,
    slots: ["1I", "T77"],
    when: "30/06 · 22:00 · Nova Iorque",
    thirdFromGroups: "C/D/F/G/H",
    channels: ["s1", "s5", "lm"],
  },
  {
    id: 78,
    slots: ["2E", "2I"],
    when: "30/06 · 18:00 · Dallas",
    channels: ["s5"],
  },
  {
    id: 79,
    slots: ["1A", "T79"],
    when: "01/07 · 02:00 · Cidade do México",
    thirdFromGroups: "C/E/F/H/I",
    channels: ["s5"],
  },
  {
    id: 80,
    slots: ["1L", "T80"],
    when: "01/07 · 17:00 · Atlanta",
    thirdFromGroups: "E/H/I/J/K",
    channels: ["s5"],
  },
  {
    id: 81,
    slots: ["1D", "T81"],
    when: "02/07 · 01:00 · Baía de SF",
    thirdFromGroups: "B/E/F/I/J",
    channels: ["s5"],
  },
  {
    id: 82,
    slots: ["1G", "T82"],
    when: "01/07 · 21:00 · Seattle",
    thirdFromGroups: "A/E/H/I/J",
    channels: ["rtp", "s1", "s5", "lm"],
  },
  {
    id: 83,
    slots: ["2K", "2L"],
    when: "03/07 · 00:00 · Toronto",
    channels: ["sic", "s1", "s5", "lm"],
  },
  {
    id: 84,
    slots: ["1H", "2J"],
    when: "02/07 · 20:00 · Los Angeles",
    channels: ["s5"],
  },
  {
    id: 85,
    slots: ["1B", "T85"],
    when: "03/07 · 04:00 · Vancouver",
    thirdFromGroups: "E/F/G/I/J",
    channels: ["s5"],
  },
  {
    id: 86,
    slots: ["1J", "2H"],
    when: "03/07 · 23:00 · Miami",
    channels: ["tvi", "s1", "s5", "lm"],
  },
  {
    id: 87,
    slots: ["1K", "T87"],
    when: "04/07 · 02:30 · Kansas City",
    thirdFromGroups: "D/E/I/J/L",
    channels: ["s5"],
  },
  {
    id: 88,
    slots: ["2D", "2G"],
    when: "03/07 · 19:00 · Dallas",
    channels: ["s5"],
  },
  {
    id: 89,
    slots: ["W74", "W77"],
    when: "04/07 · 22:00 · Filadélfia",
    channels: ["sic", "lm", "s1", "s5"],
  },
  {
    id: 90,
    slots: ["W73", "W75"],
    when: "04/07 · 18:00 · Houston",
    channels: ["s5"],
  },
  {
    id: 91,
    slots: ["W76", "W78"],
    when: "05/07 · 21:00 · Nova Iorque",
    channels: ["s5"],
  },
  {
    id: 92,
    slots: ["W79", "W80"],
    when: "06/07 · 01:00 · Cidade do México",
    channels: ["s5"],
  },
  {
    id: 93,
    slots: ["W83", "W84"],
    when: "06/07 · 20:00 · Dallas",
    channels: ["rtp", "s1", "s5", "lm"],
  },
  {
    id: 94,
    slots: ["W81", "W82"],
    when: "07/07 · 01:00 · Seattle",
    channels: ["s5"],
  },
  {
    id: 95,
    slots: ["W86", "W88"],
    when: "07/07 · 17:00 · Atlanta",
    channels: ["s5"],
  },
  {
    id: 96,
    slots: ["W85", "W87"],
    when: "07/07 · 21:00 · Vancouver",
    channels: ["s5"],
  },
  {
    id: 97,
    slots: ["W89", "W90"],
    when: "09/07 · 21:00 · Boston",
    channels: ["s1", "s5"],
  },
  {
    id: 98,
    slots: ["W93", "W94"],
    when: "10/07 · 20:00 · Los Angeles",
    channels: ["s1", "s5"],
  },
  {
    id: 99,
    slots: ["W91", "W92"],
    when: "11/07 · 22:00 · Miami",
    channels: ["s5"],
  },
  {
    id: 100,
    slots: ["W95", "W96"],
    when: "12/07 · 02:00 · Kansas City",
    channels: ["s5"],
  },
  {
    id: 101,
    slots: ["W97", "W98"],
    when: "14/07 · 20:00 · Dallas",
    channels: ["s1", "s5"],
  },
  {
    id: 102,
    slots: ["W99", "W100"],
    when: "15/07 · 20:00 · Atlanta",
    channels: ["s"],
  },
  {
    id: 103,
    slots: ["L101", "L102"],
    when: "18/07 · 22:00 · Miami",
    channels: ["s"],
  },
  {
    id: 104,
    slots: ["W101", "W102"],
    when: "19/07 · 20:00 · Nova Iorque",
    channels: ["rtp", "s", "lm"],
  },
];
const KNOCKOUT_BY_ID = {};
KNOCKOUT_MATCHES.forEach((match) => {
  KNOCKOUT_BY_ID[match.id] = match;
});

/* Visual layout of the bracket grid: which matches go in each column,
   and how many grid rows each match box spans. */
const BRACKET_COLUMNS = [
  {
    column: 1,
    rowSpan: 1,
    matchIds: [74, 77, 73, 75, 83, 84, 81, 82, 76, 78, 79, 80, 86, 88, 85, 87],
  }, // round of 32
  { column: 2, rowSpan: 2, matchIds: [89, 90, 93, 94, 91, 92, 95, 96] }, // round of 16
  { column: 3, rowSpan: 4, matchIds: [97, 98, 99, 100] }, // quarter-finals
  { column: 4, rowSpan: 8, matchIds: [101, 102] }, // semi-finals
];
const FINAL_MATCH_ID = 104,
  THIRD_PLACE_MATCH_ID = 103;
